[package]
name = "evedb"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
calamine = { version = "0.32.0", features = ["chrono"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
anyhow = "1.0.100"
zip = "6.0.0"
text-block-macros = "0.2.0"
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
h3o = "0.9.3"

[profile.release]
panic = 'abort'
